### ISSUE TITLE
Specify multiple GPUs in a single run?

### ISSUE THREAD

**Issue by Junjie-hunt** [SBQ-1999/CryFold#2]
May I know if I can specify multiple GPUs in a single run? If so, could you please let me know the command?

Thank you so much,
Junjie

**Comment by SBQ-1999** [comment]
Hi Junjie,
Sorry, the current version does not support multi-GPU operation, but we expect to enable this feature in future versions.
Currently, you can balance memory usage and runtime by adjusting the size of batch_size. A larger batch_size requires more memory but results in shorter runtime. Conversely, reducing the batch_size can decrease memory requirements.
The size of batch_size in UNet can be adjusted by editing the config.json file in the CryFold directory (you can use Notepad for editing), while the batch_size for CryNet can be specified using the parameter -n. The complete command is as follows:
```
conda activate CryFold
build -v map.mrc -o out -c .../config.json -n 1200
```
The number 1200 represents the batch_size for CryNet, and this number can be adjusted to another value.

Best regards,
Baoquan.

**Comment by Junjie-hunt** [comment]
Hi Baoquan,

Thank you so much for your quick response. Could you please explain the differences in the batch_size between UNet and CryNet modules when you have a chance?
Actually, I have used it on my project, and it has been working very well so far. However, I think there is still a lot of information about the usage of the parameters existed in this software that I don't know. Therefore, may I ask if there is a document guiding users on how to use it well? If there is, could you share it with me please?

Thank you so much,
Junjie

**Comment by Junjie-hunt** [comment]
In addition, I found that this method doesn't seem to consider the steric hindrance during the modelling. Is this true? If not, what specific parameter I can use to solve this issue?
![Doesn't consider clashes](https://github.com/user-attachments/assets/db744d80-39a8-4f85-b33a-5651ba3c881e)

Thanks,
Junjie

**Comment by SBQ-1999** [comment]
Hi Junjie,

Thank you very much for your feedback! I have updated the entire project. I added a list of FAQs in the README, hoping it can help you. 

As for the atomic clash issue, I have updated CryFold and imposed stronger constraints on it. In regions with relatively low resolution in the density map, the randomness of predictions is more likely to lead to such atomic clashes. Running CryFold again may resolve this atomic clash issue due to randomness. Therefore, one of my suggestions is to run CryFold multiple times and choose the best model. If you want to manually intervene in this issue, another suggestion is to modify the "repeat_per_residue" in config.json to 4, allowing CryFold more time to fold the proteins in that area and reducing the occurrence of atomic clashes.

Finally, CryFold is very honored to be able to assist you. Wishing you and your project good luck!

Best regards,
Baoquan.

**Comment by Junjie-hunt** [comment]
Thank you for your time, Baoquan. This is very helpful. 
I have adjusted parameters you recommended and am running the latest version of CryFold. I will keep you updated. Apart from that, I am wondering whether this calculation method can also work with the density map postprocessed by deep-learning tools, such as DeepEnhancer and EMReady. If so, how will the generated atomic model be compared to using the raw map? 

Best,
Junjie

**Comment by SBQ-1999** [comment]
Hi Junjie, I think this is a very good idea. Intuitively, higher quality density maps would produce higher quality models. However, since the training data for CryFold comes from EMDB, I’m not sure how much difference there will be between the maps processed by deep learning tools and those in EMDB. In any case, I think this is an idea worth trying. If you have done some related attempts, please let me know how they performed. Thanks!

Best,
Baoquan.
